CREATE TABLE [dbo].[UserTeam]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[TeamId] UNIQUEIDENTIFIER NOT NULL,
	[UserId] UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT [FK_UserTeam_Team] FOREIGN KEY ([TeamId]) REFERENCES dbo.Team([Id]),
	CONSTRAINT [FK_UserTeam_User] FOREIGN KEY ([UserId]) REFERENCES dbo.aspnet_Users([UserId]),
	CONSTRAINT [PK_UserTeam] PRIMARY KEY (Id),
	CONSTRAINT [IX_UserTeam] UNIQUE (Id)
)
