//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.PositionSkillGroup = new HashSet<PositionSkillGroup>();
            this.TeamPosition = new HashSet<TeamPosition>();
            this.UserPosition = new HashSet<UserPosition>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PositionSkillGroup> PositionSkillGroup { get; set; }
        public virtual ICollection<TeamPosition> TeamPosition { get; set; }
        public virtual ICollection<UserPosition> UserPosition { get; set; }
    }
}
