//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillGroup
    {
        public SkillGroup()
        {
            this.PositionSkillGroup = new HashSet<PositionSkillGroup>();
            this.Skill = new HashSet<Skill>();
            this.TeamSkillGroup = new HashSet<TeamSkillGroup>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PositionSkillGroup> PositionSkillGroup { get; set; }
        public virtual ICollection<Skill> Skill { get; set; }
        public virtual ICollection<TeamSkillGroup> TeamSkillGroup { get; set; }
    }
}
