//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public Quarter()
        {
            this.SkillLevel = new HashSet<SkillLevel>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int Year { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SkillLevel> SkillLevel { get; set; }
    }
}
