//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSkillGroup
    {
        public System.Guid Id { get; set; }
        public System.Guid TeamId { get; set; }
        public System.Guid GroupId { get; set; }
    
        public virtual SkillGroup SkillGroup { get; set; }
        public virtual Team Team { get; set; }
    }
}
