//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.TeamPosition = new HashSet<TeamPosition>();
            this.TeamSkillGroup = new HashSet<TeamSkillGroup>();
            this.UserTeam = new HashSet<UserTeam>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string Code { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<TeamPosition> TeamPosition { get; set; }
        public virtual ICollection<TeamSkillGroup> TeamSkillGroup { get; set; }
        public virtual ICollection<UserTeam> UserTeam { get; set; }
    }
}
